# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false
format = '''$directory$pixi$git_branch$git_status$hostname$cmd_duration$fill
'''
right_format = ''''''

[directory]
format = '[ $path ]($style)'
style = 'fg:black bg:cyan'
disabled = false
truncation_length = 10
truncate_to_repo = true
truncation_symbol = '󱀝/'

[character]
success_symbol = '[ I ](fg:black bg:cyan)'
error_symbol= '[ I ](fg:black bg:cyan)'
vimcmd_symbol = '[ N ](fg:black bg:cyan)'
# [character]
# success_symbol = '[](bold cyan)'
# error_symbol = '[](bold red)'
# vimcmd_symbol = '[](bold green)'

[fill]
# [](cyan)[ 󱞩](fg:black bg:cyan)[█](cyan) 
# symbol = '█ '
# symbol = '  █  '
symbol = ' '
style = 'blue'

[pixi]
disabled = false
format = '[ 󰾡󰧲 $environment ]($style)'
style = 'fg:black bg:red'

[git_branch]
disabled = false
always_show_remote = true
format = '[  $branch]($style)'
style = 'fg:black bg:green'

[git_status]
disabled = false
format = '[\[$all_status\] ]($style)'
style = 'fg:black bg:green'

[cmd_duration]
disabled = false
min_time = 1_000
show_milliseconds = false
format = '[ $duration ]($style)'
style = 'fg:black bg:cyan'

[cmake]
disabled = false
format = '$symbol($version)'

[cpp]
disabled = false
format = '$symbol($version)'

[c]
disabled = false
format = '$symbol($version)'

[python]
disabled = false
format = '$symbol($version)'

[conda]
disabled = false
format = '$symbol($version)'

[lua]
disabled = false
format = '$symbol($version)'

[typst]
disabled = false
format = '$symbol($version)'

[rlang]
disabled = false
format = '$symbol($version)'

[zig]
disabled = false
format = '$symbol($version)'

[rust]
disabled = false
format = '$symbol($version)'

[quarto]
disabled = false
format = '$symbol($version)'

[package]
disabled = true

[hostname]
disabled = false
ssh_only = false
format = '[ $ssh_symbol$hostname ]($style)'
style = 'fg:black bg:cyan'

[time]
disabled = true
format = '[\[$time\]]($style)'
time_format = '%b %e %R'
style = 'bold cyan'
